---
- name: Install and Configure Grafana with Prometheus datasource and Node Exporter Dashboard
  hosts: grafana_server
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

    grafana_admin_user: "admin"
    grafana_admin_password: "admin"
    grafana_port: 3000

    prometheus_server_url: "http://0.0.0.0:9090"
    grafana_nodeexporter_dashboard_id: 1860
    grafana_dashboard_folder: "Infrastructure Monitoring"

  tasks:
    ####################################################################
    #  Add Grafana Repository
    ####################################################################
    - name: Add Grafana YUM repository
      ansible.builtin.yum_repository:
        name: grafana
        description: Grafana OSS YUM Repository
        baseurl: https://packages.grafana.com/oss/rpm
        gpgcheck: yes
        repo_gpgcheck: yes
        enabled: yes
        gpgkey: https://packages.grafana.com/gpg.key

    ####################################################################
    #  Install Grafana
    ####################################################################
    - name: Install Grafana
      ansible.builtin.yum:
        name: grafana
        state: present

    ####################################################################
    #  Enable and Start Grafana
    ####################################################################
    - name: Enable and start Grafana
      ansible.builtin.systemd:
        name: grafana-server
        enabled: yes
        state: started
        daemon_reload: yes

    ####################################################################
    #  Wait for Grafana API availability
    ####################################################################
    - name: Wait until Grafana API is available
      ansible.builtin.uri:
        url: "http://localhost:{{ grafana_port }}/api/health"
        status_code: 200
      register: grafana_status
      retries: 15
      delay: 5
      until: grafana_status.status == 200

    ####################################################################
    #  Detect if Grafana still has default admin password
    ####################################################################
    - name: Check Grafana login using default credentials
      ansible.builtin.uri:
        url: "http://localhost:{{ grafana_port }}/api/login/ping"
        user: "admin"
        password: "admin"
        force_basic_auth: yes
        status_code: 200,401
      register: grafana_default_check
      failed_when: false

    ####################################################################
    #  Reset password if default still active
    ####################################################################
    - name: Reset Grafana admin password (only if default is active)
      ansible.builtin.command: >
        grafana-cli admin reset-admin-password {{ grafana_admin_password }}
      when: grafana_default_check.status == 200
      notify: restart grafana

    ####################################################################
    #  Wait for Grafana restart
    ####################################################################
    - name: Wait until Grafana API is healthy after password reset
      ansible.builtin.uri:
        url: "http://localhost:{{ grafana_port }}/api/health"
        status_code: 200
      register: grafana_status_after_reset
      retries: 15
      delay: 5
      until: grafana_status_after_reset.status == 200

    ####################################################################
    #  Add Prometheus datasource
    ####################################################################
    - name: Add Prometheus datasource to Grafana
      community.grafana.grafana_datasource:
        name: "Prometheus-CDP"
        url: "http://localhost:{{ grafana_port }}"
        url_username: "{{ grafana_admin_user }}"
        url_password: "{{ grafana_admin_password }}"
        ds_type: "prometheus"
        access: "proxy"
        ds_url: "{{ prometheus_server_url }}"
        is_default: true

    ####################################################################
    #  Download Node Exporter dashboard JSON
    ####################################################################
    - name: Download Node Exporter dashboard JSON from Grafana.com
      ansible.builtin.get_url:
        url: "https://grafana.com/api/dashboards/{{ grafana_nodeexporter_dashboard_id }}/revisions/latest/download"
        dest: "/tmp/nodeexporter_dashboard.json"
        mode: '0644'

    ####################################################################
    # Replace datasource placeholder with Prometheus-CDP
    ####################################################################
    - name: Replace datasource placeholder with Prometheus-CDP
      ansible.builtin.replace:
        path: /tmp/nodeexporter_dashboard.json
        regexp: '"datasource": *null'
        replace: '"datasource": "Prometheus-CDP"'

    ####################################################################
    #  Ensure the dashboard folder exists
    ####################################################################
    - name: Ensure Grafana folder exists
      community.grafana.grafana_folder:
        url: "http://localhost:{{ grafana_port }}"
        url_username: "{{ grafana_admin_user }}"
        url_password: "{{ grafana_admin_password }}"
        title: "{{ grafana_dashboard_folder }}"
        state: present

    ####################################################################
    #  Import the Node Exporter dashboard
    ####################################################################
    - name: Import Node Exporter Full dashboard
      community.grafana.grafana_dashboard:
        url: "http://localhost:{{ grafana_port }}"
        url_username: "{{ grafana_admin_user }}"
        url_password: "{{ grafana_admin_password }}"
        state: present
        overwrite: true
        path: "/tmp/nodeexporter_dashboard.json"
        folder: "{{ grafana_dashboard_folder }}"

  handlers:
    - name: restart grafana
      ansible.builtin.systemd:
        name: grafana-server
        state: restarted

